---
- hosts: all
  become: true
  pre_tasks:
      - name: update repo cache (CentOS)
        tags: always
        dnf:
            udate_cache: yes
        changed_when: false
        when: ansible_distribution == "CentOS"

      - name: update repo cache (Ubuntu)
        tags: always
        apt:
            update_cache: yes
        changed_when: false
        when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
      - name: add ssh key for ansible user
        tags: always
        authorized_key:
            user: ansible-user
            key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDylil2y1icH5gmDd0wJPlFJZ7ELGY7YD+ORpVLnahfE6PTncHpfZrJzVG+lMJ7DAuy0UnSMjpyAimumImmtfBBDAZ4YBIhLkfivEMSRtLcr3SyiAjr53Qp5JNKEVFxVsXHnbXhLPMwnpON5vZND1Qns3tEYRxR7Jheis7VvdoT0N+tEojgCGnN4arytVj4vEatsCHDrJaZ06UtoCn09bOCCZWazQOgkHsChoXdc0tdcfZEn8Ha5+xKFyWwYFrRU71NBGuRsuOA8JMa9JvecoEtgBDJlN0HA8kbblzG08Wmk+TJ5r4McBv5u53fjmqzab5G8c6V2ljnb4tYuhFnu0/AwCZPDDm6hIy4bVSBShWqAnqYDcV092k/I52YoyqxgStJLLA0uCaIRC0arBCs6epomJjFfKlEcKyZn4Z3F+iYHUJwjViJIbSsP0CSItJDpnR0dLd52ph50QP4zSMvUR0xPJ+U1TL4AyFjDgxYfhHtrMUlZc409HG9GJo7ujhrtzLZDUjQDk9Eum/lKl2Jgjc7HpD2MtAbOfRwHTlpbbSohUYl8S8t4u9aIg/AWpwqDnWgTSyz1Om81IyVSYgsBMuX82rBxaIV18+Jts86PmqWjlB04EVsdIdsFacMMxxWitdbJT4AiyhrvVaV3/ebKsMMReL/Hmi9ItPOuhBY7L9uiQ== ansible'

- hosts: workstations
  become: true
  tasks:
      - name: install unzip
        package:
            name: unzip

      - name: install terraform
        unarchive:
            src: https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip
            dest: /usr/local/bin
            remote_src: yes
            mode: 0755
            owner: root
            group: root

- hosts: web_servers
  become: true
  tasks:
      - name: install apache and php for Ubuntu Servers
        tags: ubuntu,apache,apache2
        apt:
            name:
                - apache2
                - libapache2-mod-php
            state: latest
        when: ansible_distribution == "Ubuntu"

      - name: install apache and php for CentOS Servers
        tags: centos,apache,httpd
        dnf:
            name:
                - httpd
                - php
            state: latest
        when: ansible_distribution == "CentOS"

      - name: start httpd (CentOS)
        tags: centos,apache,httpd
        service:
            name: httpd
            state: started
            enabled: yes
        when: ansible_distribution == "CentOS"

      - name: copy default html file for site
        tags: apache,apache2,httpd
        copy:
            src: default_site.html
            dest: /var/www/html/index.html
            owner: root
            group: root
            mode: 0644

- hosts: db_servers
  become: true
  tasks:
      - name: install mariadb package (CentOS)
        tags: centos,db,mariadb
        dnf:
            name: mariadb
            state: latest
        when: ansible_distribution == "CentOS"

      - name: install mariadb package (Ubuntu)
        tags: ubnuntu,db,mariadb
        apt:
            name: mariadb-server
            state: latest
        when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
      - name: install samba package
        tags: samba
        package:
            name: samba
            state: latest
